### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by HXavS** [203x/figma-border#7]
- [ ] Add Shape objects

- [ ] Add Hex Color Option

- [ ] Add Internal/ External border logic/ option
